#!/bin/bash
while getopts s:g:w: option
do
    case "${option}" in
        s) sample_file=${OPTARG} ;;
        g) reference=${OPTARG} ;;
        w) workspace=${OPTARG} ;;
    esac
done

function check_file {
    file=$1
    msg=$2
    if [[ ! -e ${file} ]]; then
        echo "${msg} not exists: ${file}"
        exit 1
    fi
}

function check_dir {
    if [[ ! -e $1 ]]; then
        echo "${2} not exists: $1"
        exit 1
    fi
}

check_file ${sample_file} "sample file"
check_file ${reference} "reference genome file"
check_dir ${workspace} "workspece directory"

echo "sample file: ${sample_file}"
echo "reference: ${reference}"
echo "workspace: ${workspace}"

module load numpy
module load samtools
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
python ${SCRIPT_DIR}/FetchSRA.py ${sample_file} ${workspace}
python ${SCRIPT_DIR}/DumpSRA.py ${sample_file} ${workspace}
python ${SCRIPT_DIR}/SmaltMap.py ${sample_file} ${reference} ${workspace}
bash ${SCRIPT_DIR}/InvokeFreebayes.sh ${sample_file} ${reference} ${workspace}
bash ${SCRIPT_DIR}/ConcensusGenome.sh ${sample_file} ${reference} ${workspace}

exit 0;
